version: '3.4'

services:
    app:
        image: oxatis/oxatis-php:app
        build:
            context: .
            target: app
        networks:
            - egress
        volumes:
            - /srv/app/var/
            - /srv/app/var/cache/
            - /srv/app/var/logs/
            - /srv/app/var/sessions/

    webserver:
        image: oxatis/oxatis-php:webserver
        build:
            context: .
            target: webserver
        ports:
            - "8000:80"
        networks:
            egress:
            ingress:
                aliases:
                    - localhost-antiquaire.com
networks:
    ingress: # network to outside
        driver: bridge
    egress: # network to inside
        driver: bridge
