version: '3.4'

services:
    app:
        volumes:
            - ${PWD-.}/:/srv/app:rw,cached

    webserver:
        volumes:
            - ${PWD-.}/nginx.conf:/etc/nginx/conf.d/default.conf
            - ${PWD-.}/public:/srv/app/public:ro
